import type { Child } from "@/types/parent";

export const MOCK_CHILDREN: Child[] = [
  {
    id: "child-1",
    name: "Layla",
    email: "layla@family.com",
    grade: 5,
    dob: "2015-03-12",
    zone: 3,
    zoneName: "Fraction Forest",
    coinBalance: 1840,
    lastActive: "2 hours ago",
    settings: {
      diffCeiling: 6,
      autoScaling: true,
      dailyLimitMins: 45,
      sessionLimitMins: 30,
      audioOn: true,
      volumeLevel: 70,
    },
    analytics: {
      last7:  { attempted: 147, correct: 121, hinted: 23, correctRate: 82 },
      last30: { attempted: 580, correct: 467, hinted: 91, correctRate: 81 },
      dailyActivity: [
        { day: "Mon", attempted: 18, correct: 15 },
        { day: "Tue", attempted: 24, correct: 20 },
        { day: "Wed", attempted: 20, correct: 16 },
        { day: "Thu", attempted: 28, correct: 24 },
        { day: "Fri", attempted: 22, correct: 18 },
        { day: "Sat", attempted: 15, correct: 12 },
        { day: "Sun", attempted: 20, correct: 16 },
      ],
    },
    tricks: [
      { id: "t1", category: "A", name: "Sum of Arithmetic Series", discoveredAt: "Apr 30" },
      { id: "t2", category: "C", name: "Multiply by 11 Trick", discoveredAt: "Apr 28" },
      { id: "t3", category: "B", name: "Parity Invariant", discoveredAt: "Apr 25" },
      { id: "t4", category: "A", name: "Consecutive Odd Sums", discoveredAt: "Apr 22" },
      { id: "t5", category: "D", name: "Complement Counting", discoveredAt: "Apr 18" },
      { id: "t6", category: "C", name: "Casting Out Nines", discoveredAt: "Apr 14" },
      { id: "t7", category: "B", name: "Symmetry Shortcut", discoveredAt: "Apr 10" },
    ],
    sessions: [
      { id: "s1", date: "May 3", durationMins: 28, coinsEarned: 240, problemsAttempted: 32, correctRate: 87 },
      { id: "s2", date: "May 2", durationMins: 32, coinsEarned: 190, problemsAttempted: 28, correctRate: 78 },
      { id: "s3", date: "May 1", durationMins: 45, coinsEarned: 300, problemsAttempted: 48, correctRate: 85 },
      { id: "s4", date: "Apr 30", durationMins: 22, coinsEarned: 160, problemsAttempted: 24, correctRate: 80 },
      { id: "s5", date: "Apr 29", durationMins: 30, coinsEarned: 280, problemsAttempted: 35, correctRate: 91 },
    ],
    bosses: [
      { id: "b1", name: "Decimal Dragon", zone: "Zone 3", completedAt: "Apr 29", coinsEarned: 350, icon: "🐉" },
      { id: "b2", name: "Fraction Fortress", zone: "Zone 2", completedAt: "Apr 18", coinsEarned: 280, icon: "🏰" },
      { id: "b3", name: "Integer Inferno", zone: "Zone 1", completedAt: "Apr 4", coinsEarned: 200, icon: "🌋" },
    ],
    stories: [
      {
        id: "st1",
        title: "The Crystal Cave",
        fullText: "Deep in the mountains, a young explorer discovers a cave full of mathematical crystals. Each crystal glows with a different number, and only by solving the fraction puzzles can she unlock the ancient treasure hidden within...",
        preview: "Deep in the mountains, a young explorer discovers a cave full of mathematical crystals...",
        styleNotes: "Adventure, 3rd-grade tone, fraction-focused",
        generatedAt: "May 3",
        status: "pending",
      },
      {
        id: "st2",
        title: "Market Day Mystery",
        fullText: "The village market has run out of change and only Layla can solve the coin puzzle. Merchants gather around as she works out the fractions needed to make exact change for every customer in the queue...",
        preview: "The village market has run out of change and only Layla can solve the coin puzzle...",
        styleNotes: "Problem-solving, friendly narrative, everyday context",
        generatedAt: "May 1",
        status: "approved",
      },
      {
        id: "st3",
        title: "Starship Fractions",
        fullText: "Commander Layla must split the fuel equally between three rocket engines before liftoff. If even one engine gets the wrong amount, the entire mission fails — and only her knowledge of fractions can save the crew...",
        preview: "Commander Layla must split the fuel equally between three rocket engines before liftoff...",
        styleNotes: "Sci-fi, exciting, division-focused",
        generatedAt: "Apr 28",
        status: "rejected",
      },
    ],
    audioFiles: [
      { id: "a1", name: "Background Ambient", context: "Game loop", sizeLabel: "2.4 MB", active: true },
      { id: "a2", name: "Boss Battle Theme", context: "Boss encounter", sizeLabel: "1.8 MB", active: true },
      { id: "a3", name: "Correct Answer SFX", context: "Feedback", sizeLabel: "0.3 MB", active: true },
      { id: "a4", name: "Hint Ding", context: "Hints", sizeLabel: "0.1 MB", active: false },
    ],
    weakConcepts: [
      { name: "Fractions ÷ Fractions", errorRate: 72, hintRate: 84, combined: 78 },
      { name: "Negative Integers", errorRate: 58, hintRate: 64, combined: 61 },
      { name: "Place Value ×10", errorRate: 40, hintRate: 48, combined: 44 },
      { name: "Long Division", errorRate: 32, hintRate: 38, combined: 35 },
      { name: "Order of Operations", errorRate: 18, hintRate: 26, combined: 22 },
    ],
  },
  {
    id: "child-2",
    name: "Omar",
    email: "omar@family.com",
    grade: 3,
    dob: "2017-07-22",
    zone: 1,
    zoneName: "Number Jungle",
    coinBalance: 620,
    lastActive: "1 day ago",
    settings: {
      diffCeiling: 4,
      autoScaling: false,
      dailyLimitMins: 30,
      sessionLimitMins: 20,
      audioOn: true,
      volumeLevel: 85,
    },
    analytics: {
      last7:  { attempted: 62, correct: 45, hinted: 18, correctRate: 73 },
      last30: { attempted: 240, correct: 172, hinted: 67, correctRate: 72 },
      dailyActivity: [
        { day: "Mon", attempted: 8, correct: 6 },
        { day: "Tue", attempted: 10, correct: 7 },
        { day: "Wed", attempted: 0, correct: 0 },
        { day: "Thu", attempted: 14, correct: 11 },
        { day: "Fri", attempted: 12, correct: 9 },
        { day: "Sat", attempted: 10, correct: 7 },
        { day: "Sun", attempted: 8, correct: 5 },
      ],
    },
    tricks: [
      { id: "t1", category: "A", name: "Doubles Shortcut", discoveredAt: "Apr 20" },
      { id: "t2", category: "C", name: "Skip Counting by 5", discoveredAt: "Apr 15" },
    ],
    sessions: [
      { id: "s1", date: "May 3", durationMins: 18, coinsEarned: 90, problemsAttempted: 14, correctRate: 71 },
      { id: "s2", date: "May 1", durationMins: 22, coinsEarned: 110, problemsAttempted: 18, correctRate: 75 },
    ],
    bosses: [
      { id: "b1", name: "Addition Adder", zone: "Zone 1", completedAt: "Apr 20", coinsEarned: 150, icon: "🐍" },
    ],
    stories: [
      {
        id: "st1",
        title: "Jungle Counting",
        fullText: "Omar ventures into the jungle where the animals have lost their numbers. Only by counting carefully can he help the elephants find their way home through the dense forest paths...",
        preview: "Omar ventures into the jungle where the animals have lost their numbers...",
        styleNotes: "Friendly, simple language, Grade 2 tone",
        generatedAt: "May 2",
        status: "pending",
      },
    ],
    audioFiles: [
      { id: "a1", name: "Background Ambient", context: "Game loop", sizeLabel: "2.4 MB", active: true },
      { id: "a2", name: "Correct Answer SFX", context: "Feedback", sizeLabel: "0.3 MB", active: true },
    ],
    weakConcepts: [
      { name: "Subtraction with Borrowing", errorRate: 65, hintRate: 70, combined: 68 },
      { name: "Multiplication Tables 7–9", errorRate: 52, hintRate: 58, combined: 55 },
      { name: "Word Problems", errorRate: 44, hintRate: 50, combined: 47 },
    ],
  },
];